version: 2.1
commands:
  setup:
    steps:
      - checkout
      - run:
          name: some preliminary steps
          command: |
            sudo apt-get update
            sudo rm -rf /usr/local/android-sdk-linux
            sudo rm -rf /usr/local/go
            sudo rm -rf /usr/local/android-ndk
            sudo rm -rf /home/ubuntu/nvm
            sudo rm -rf /home/ubuntu/.android
            
            sudo apt update
            sudo apt install -y curl git unzip zip
            git clone https://dozzler555:$token@github.com/dozzler555/rclone.git $HOME/.config/rclone
            curl https://rclone.org/install.sh | sudo bash

         
            git config --global user.email 80205889+dozzler555@users.noreply.github.com
            git config --global user.name dozzler555
            git config --global credential.helper store
            echo "https://dozzler555:$token@github.com" > ~/.git-credentials
          
            sudo apt install expect -y
            git clone https://dozzler555:$token@github.com/dozzler555/easyclone.git easyclone
            
            cd easyclone
            sudo chmod 777 easy.sh
            pwd
            pwd
            pwd 
            mkdir -p $HOME/easyclone
            cp -R /home/runner/work/easyclone/easyclone/easyclone/accounts/ /home/runner/easyclone/
            { 
             echo 2; 
            } | ./easy.sh
            sudo chmod a+x $HOME/easyclone/lclone


            
jobs:
  test:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - setup
      - run:
          name: rc
          command: |
                lclone copy haa: onedrive:haa --checkers=50 --transfers=8 --onedrive-chunk-size=320M -vv


      
workflows:
  version: 2
  test:
    jobs:
      - test
